config/routes.rb
Rails.application.routes.draw do
  post 'events/create'
  get 'events/show'

  root 'welcome#index'
  get '/gettingstarted', to: 'welcome#gettingstarted' 

  resources :sensors
  resources :notes
  resources :sessions
  resources :users

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def gettingstarted

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_header.html.erb
<!-- <header class="header">
  <nav class="sign" class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Logo</a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to 'Sign in', new_session_path  %></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><%= link_to 'Sign in', new_session_path  %></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</header> -->


<!-- <nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a href="collapsible.html">Javascript</a></li>
      <li><a href="mobile.html">Mobile</a></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a href="collapsible.html">Javascript</a></li>
      <li><a href="mobile.html">Mobile</a></li>
    </ul>
  </div>
</nav> -->

app/views/welcome/gettingstarted.html.erb
<div class="col l6 s12">
  <div class="container">
    <div class="row center">
      <h1 style="color: #ff9800;">Getting Started</h1>
      <br>
      <p style="text-align: justify">
        We have organized a series of activities into projects in order to help
        in getting you started. The easiest way to verify that you have set up
        your account properly is to start with the first project and proceed
        from there. The sensors we use as examples are part of the SunFounder
        sensor kit, but any sensor would work. Let's start with Projects 1 and
        2 to verify the Pi is set up properly.
      </p>
      <br><br>
      <h4 style="color: #ff9800;">Project 1 - Raspberry Pi</h4>

      <ol style="text-align: left;">
        <li>Log into your account and take note of your API key.
          This key will allow you to upload data to Sensoree.
          Start out by adding a new sensor of type Internet.
          Technically not a sensor,
          we'll start out by having the Pi send ping data to the servers.
          A ping is a way to test connectivity across the Internet.
          The Raspberry Pi will ping a server,
          and then send to Sensoree,
          the amount of time it took to reach that server
          (measured in milliseconds).</li>
        <li>On the Raspberry Pi,
          you may need to reinstall the ping utility if
          your user account doesn't have access.
          By default, the user pi, doesn't have access.
          You can give pi access by issuing:</li>
      </ol>
      <div class="indented-steps">
        <div class="code-text">sudo apt-get install --reinstall iputils-ping</div>
        <div>Test the ping: <span class="code-text">ping google.com</span></div>
        <div>Go to the following link to retrieve the full source code. <a href="https://github.com/davidkarim/sensoree-pi">https://github.com/davidkarim/sensoree-pi</a></div>
      </div>

      <h4 style="color: #ff9800;">Project 2 - Temperature Sensor</h4>


    <ol style="text-align: left;">
    <li>After validating that the previous project is sending data to Sensoree,
      let's now configure a temperature sensor from the Sunfounder kit.
      Start out by cloning the wiringPi repsitory from GitHub.</li>
    <p><span class="code-text">git clone git:://git.drogon.net/wiringPi</span></p>
      <li>Install wiringPi: </li>
      <p><span class="code-text">cd wiringPi</span></p>
      <p><span class="code-text">git pull origin ./build</span></p>
      <li>Now edit the <span class="code-text">/boot/config.txt</span> file to add hardware access
        through <span class="code-text">/sys/bus</span> directory.</li>
      <li>Add the following to the <span class="code-text">/boot/config.txt</span> file: </li>
      <p><span class="code-text">dtoverlay=w1-gpio</span></p>
      <li>Reboot your device: <span class="code-text">sudo reboot</span></li>
      <li>After the device has been rebooted, issue the following commands
        to mount the device drivers:</li>
          <p><span class="code-text">sudo modprobe w1-gpio</span></p>
          <p><span class="code-text">sudo modprobe w1-therm</span></p>
      </li>
      <li>  Now connect the thermometer sensor to the Pi. Navigate to the
        device directory:
        <span class="code-text">cd /sys/bus/w1/devices/ls</span>
      </li>
      <li>Have a look at the devices shown,
        there should be a numeric directory such as <span class="code-text">28-041623a757ff</span>.
        Change to that directory: <span class="code-text">cd 28-041623a757ff</span></li>
      <li>To display a reading, issue the following command,
        while in that directory: <span class="code-text">cat w1_slave</span></li>
      <li>The following output, verifies a reading (your output will be slightly different):
        <div class="indented-steps">7a 01 4b 46 7f ff 0c 10 ec : crc=ec YES
        7a 01 4b 46 7f ff 0c 10 ec t=23625</div>
      </li>
      <li>Dividing the t value by 1000 gives the Celsius reading.
        Now in order to send these values to Sensoree,
        go to the following link to download the source code. link</li>
      </ol>


        <h4 style="color: #ff9800;">Project 3 - Ultrasound Sensor</h4>


        <ol style="text-align: left;">

          <li>The ultrasound sensor's sample file is located at the Github repository:</li>
          <p><a href="https://github.com/davidkarim/sensoree-pi">https://github.com/davidkarim/sensoree-pi</a></p>
          <li>The wiring for the ultrasound sensor is defined in the file. The sample file, by default, also shows readings every half a second, but uploads to Sensoree are done every 30 seconds. Sensoree will not accept readings with a higher frequency, so its best to keep that frequency intact.</li>

        </ol>




      </p>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<%# render :partial => "header" %>

<div class="parallax-container" style="background: rgba(0, 0, 0, 0.475);">
  <div class="section no-pad-bot" class="background-image">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text">Sensoree</h1>
      <div class="row center">
        <h5 class="header col s12 light" >Your sensor data in the cloud. If you have a Raspberry Pi, Arduino, or any other type of device that is collecting data for you, Sensoree can aggregate and display the data for you.</h5>
      </div>
      <div class="row center">
        <%= link_to 'Register', new_user_path, class: "btn-large waves-effect waves-light orange" %>
      </div>
      <br><br>

      </div>
    </div>
  <div class="parallax"><%= image_tag "thumb_ras_pi_2.jpg" %></div>
</div>

<!--   Icon Section   -->
<div class="row">
  <div class="col s12 m4">
    <div class="icon-block">
      <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
      <h5 class="center">Built for Builders</h5>

      <p class="light">Set up your Internet of Things device to interface to the world. Then, send the data to Sensoree to display and connect with other services.</p>
    </div>
  </div>

  <div class="col s12 m4">
    <div class="icon-block">
      <h2 class="center brown-text"><i class="material-icons">group</i></h2>
      <h5 class="center">Share you data</h5>

      <p class="light">You'll be able to display your data with the world by setting any of your sensors as public, or keep it private and secure.</p>
    </div>
  </div>

  <div class="col s12 m4">
    <div class="icon-block">
      <h2 class="center brown-text"><i class="material-icons">settings_remote</i></h2>
      <h5 class="center">Any connection</h5>

      <p class="light">How you connect doesn't matter. Set up your device to connect via wi-fi or cellular. As long as your device can reach our app's address, you can send data.</p>
    </div>
  </div>
</div>


</div>
</div>

<div class="parallax-container valign-wrapper" style="background: rgba(0, 0, 0, 0.475);">
<div class="section no-pad-bot">
  <div class="container">
    <div class="row center">
      <h5 class="header col s12 light">Run through our projects to get started. Monitor your temperature, check when someone arrives at your home, build it yourself.</h5>
    </div>
  </div>
</div>
<div class="parallax"><%= image_tag "thumb_ras_pi_4.jpg" %></div>
</div>