config/routes.rb
Rails.application.routes.draw do
  post 'events/create'
  get 'events/show'

  root 'welcome#index'
  get '/gettingstarted', to: 'welcome#gettingstarted' 

  resources :sensors
  resources :notes
  resources :sessions
  resources :users

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  belongs_to :user
  has_many :events
  has_many :notifications

  enum unit: [:Celsius, :Fahrenheit, :centimeters, :inches, :feet, :milliseconds]
  enum kind: [:temperature, :ultrasound, :internet]
  enum type_of_graph: [:curved_line_graph, :straight_line_graph, :timeline]
  enum notification: [:no_notification, :upper_threshold, :lower_threshold]

  # Create array of two-dimensional arrays containing x and y values
  # for the graph data.
  def graph_data(events, minute_range)
    graph_data =[]
    events.each do | e |
      if (Time.now - e.capture_time) / 60 < minute_range
        graph_data << [e.capture_time, e.value]
      end
    end
    return graph_data
  end

  def notify(phone_number, event)
    count = self.notification_count || 0
    notification_window = self.notification_window || Time.now.to_s

    image_url = []
    unless event.images.empty?
      image_url = event.images.first.photo.url
    end
    if count >= 10  && Time.now - notification_window.to_time > 86400 # secs in a day
      # After 24 hours have passed, reset counter to zero, send notification
      self.notification_count = 0
      self.notification_window = Time.now
      # Send notification
      send_twilio(phone_number, event.value, image_url)
      return true
    elsif count < 10
      # Action to take as long as less than 10 notifications in a 24 hour period
      send_twilio(phone_number, event.value, image_url)
      count += 1
      self.notification_count = count
      self.notification_window = notification_window
      self.save
      return true
    elsif count >= 10  && Time.now - notification_window.to_time <= 86400 # secs in a day
      # Do not send notification, passed limit of 10 notifications per day
      # Do nothing
      return false
    end
  end

  def send_twilio(phone_number, value, image_url)
    account_sid = ENV['TWI_ACCOUNT_SID'] # Twilio Account SID
    auth_token = ENV['TWI_AUTH_TOKEN']   # Twilio Auth Token
    @client = Twilio::REST::Client.new account_sid, auth_token
    if !image_url.empty?
      message_body = "Sensor #{self.name} triggered. Value: #{value} #{self.unit}"
      message = @client.account.messages.create(:body => message_body,
          :to => "+1#{phone_number}",    # User phone number
          :from => "+19542288318",  # Twilio account phone number
          :media_url => "#{image_url}")

    else
      message_body = "Sensor #{self.name} triggered. Value: #{value} #{self.unit}"
      message = @client.account.messages.create(:body => message_body,
          :to => "+1#{phone_number}",    # User phone number
          :from => "+19542288318")  # Twilio account phone number

    end


  end

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  layout "dashboard"
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in, only: [:index, :new, :edit, :create, :update, :destroy]
  before_action :default_values, only: [:new, :create, :update, :edit]


  def index
    @sensors = current_user.sensors.all
  end

  def show
    @axis_time = params[:axis_time]
    @grouped_data = []
    case @axis_time
    when "1" # 24-hour view selected
      minute_range = 1440
      @x_format = "HH:mm a"
      @graph_data = @sensor.graph_data(@sensor.events, minute_range)
      # Group two-dimensional array of hours, by hour
      @grouped_data = @graph_data.map { |arr| [] << arr[0].beginning_of_hour << arr[1] }.uniq { |x| x[0] }
      # Disregard values. Convert hours to two-dimensional array of one hour blocks
      @grouped_data = @grouped_data.map { |x| [] << @sensor.name << x[0] << x[0].end_of_hour }
    when "2" # week view selected
      minute_range = 10080
      @x_format = "MMM d"
      @graph_data = @sensor.graph_data(@sensor.events, minute_range)
      # Group two-dimensional array of days, by day
      @grouped_data = @graph_data.map { |arr| [] << arr[0].beginning_of_day << arr[1] }.uniq { |x| x[0] }
      # Disregard values. Convert days to two-dimensional array of one day blocks
      @grouped_data = @grouped_data.map { |x| [] << @sensor.name << x[0] << x[0].end_of_day }
    when "3" # month view selected
      minute_range = 40320
      @x_format = "d"
      @graph_data = @sensor.graph_data(@sensor.events, minute_range)
      # Group two-dimensional array of days, by day
      @grouped_data = @graph_data.map { |arr| [] << arr[0].beginning_of_day << arr[1] }.uniq { |x| x[0] }
      # Disregard values. Convert days to two-dimensional array of one day blocks
      @grouped_data = @grouped_data.map { |x| [] << @sensor.name << x[0] << x[0].end_of_day }
    when "4" # year view selected
      minute_range = 483840
      @x_format = "MMM"
      @graph_data = @sensor.graph_data(@sensor.events, minute_range)
      # Group two-dimensional array of days, by day
      @grouped_data = @graph_data.map { |arr| [] << arr[0].beginning_of_day << arr[1] }.uniq { |x| x[0] }
      # Disregard values. Convert days to two-dimensional array of one day blocks
      @grouped_data = @grouped_data.map { |x| [] << @sensor.name << x[0] << x[0].end_of_day }
    else
      minute_range = 1440
      @graph_data = @sensor.graph_data(@sensor.events, minute_range)
      # Group two-dimensional array of days, by day
      @grouped_data = @graph_data.map { |arr| [] << arr[0].beginning_of_day << arr[1] }.uniq { |x| x[0] }
      # Disregard values. Convert days to two-dimensional array of one day blocks
      @grouped_data = @grouped_data.map { |x| [] << @sensor.name << x[0] << x[0].end_of_day }
    end

  end

  def new
    @sensor = current_user.sensors.new
  end

  def edit
  end

  def create
    @sensor = current_user.sensors.new(sensor_params)
    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_path, notice: 'Sensor was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      if current_user
        @sensor = current_user.sensors.find(params[:id])
      else
        # Determine if this user has set this sensor as public
        public_sensor = Sensor.find(params[:id]).public
        @sensor = Sensor.find(params[:id]) if public_sensor
      end
    end

    def default_values
      # params[:public] ||= false
      # params[:sensor][:type_of_graph] ||= 0

      # Used in the view to display humanized strings instead of snake_cased names
      # temp holds array of 2d array, Hash[] converts to single hash
      temp = Sensor.type_of_graphs.map {|key, value| [key.to_s.humanize, value]}
      @type_of_graphs = Hash[temp]
      temp = Sensor.notifications.map {|key, value| [key.to_s.humanize, value]}
      @notifications = Hash[temp]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params[:sensor][:unit] = params[:sensor][:unit].to_i
      params[:sensor][:kind] = params[:sensor][:kind].to_i
      params[:sensor][:type_of_graph] = params[:sensor][:type_of_graph].to_i
      params[:sensor][:notification] = params[:sensor][:notification].to_i
      params[:sensor][:notification_value] = params[:sensor][:notification_value].to_i
      if params[:sensor][:public] == "on"
        params[:sensor][:public] = true
      else
        params[:sensor][:public] = false
      end
      params.require(:sensor).permit(:name, :unit, :kind, :type_of_graph, :public, :notification, :notification_value)
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_sensor.html.erb
<%= form_for @sensor, html: {class: "col s12"}  do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <!-- In Sensor model, this is called kind -->
  <div class="input-field col s12">
    <%= f.label "Type of Sensor" %>
    <br>
    <%= f.select :kind, Sensor.kinds, selected: Sensor.kinds[@sensor.kind] %>
  </div>

  <div class="input-field col s12">
    <%= f.label :sensor_unit %>
    <br>
    <%= f.select :unit, Sensor.units, selected: Sensor.units[@sensor.unit] %>
  </div>

  <div class="input-field col s12">
    <% if @sensor.public %>
      <!-- Switch -->
      <div id="public-switch" class="switch">
        <label>
          Private
          <input name="sensor[public]" type="checkbox" checked>
          <span class="lever"></span>
          Public
        </label>
      </div>
    <% else %>
    <!-- Switch -->
      <div id="public-switch" class="switch">
        <label>
          Private
          <input name="sensor[public]" type="checkbox">
          <span class="lever"></span>
          Public
        </label>
      </div>
    <% end %>
  <div>

  <div class="input-field col s12">
    <%= f.label "Type of Graph" %>
    <br>
    <%= f.select :type_of_graph, @type_of_graphs, selected: Sensor.type_of_graphs[@sensor.type_of_graph] %>
  </div>

  <div class="input-field col l6 s12">
    <%= f.label "Notification" %>
    <br>
    <%= f.select :notification, @notifications, selected: Sensor.notifications[@sensor.notification] %>
  </div>

  <div class="input-field col l6 s12">
    <%= f.label "Threshold value for notifications" %><br>
    <%= f.text_field :notification_value %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn-large waves-effect waves-light orange" %>
    <br><br>
    <%= link_to 'Cancel', sensors_path %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<div class="section no-pad-bot" id="index-banner">
  <div class="container">

    <h1 class="header center orange-text">Edit Sensor</h1>
    <div class="row center">
      <h5 class="header col s12 light">

        <%= render 'sensor' %>

      </h5>
    </div>
  </div>
</div>
<% [:info, :error].each do |key| %>
  <% if flash[key] %>
  <div class="<%= key %>" id="flash">
    <%= flash[key] %>
  </div>
  <% end %>
<% end %>

app/views/sensors/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<% if flash[:notice] %>
  <div class="row">
    <div class="col s12 m12">
      <div class="card-panel teal">
        <span class="white-text"><%= flash[:notice] %>
        </span>
      </div>
    </div>
  </div>
<% end %>



<h1>Sensor Data</h1>

<div class="code-box">
  <h6>Your API Key: <%= api_key %><i
    class="tiny material-icons tooltipped"
    data-tooltip="Your private API key is used
                  to authenticate you. Use it
                  on your device every
                  time it sends data.">info_outline</i></h6>
</div>

<table class="striped" class="responsive-table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Sensor</th>
      <th>Unit</th>
      <th>Kind</th>
      <th>Graph Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.sort.each do |sensor| %>
      <tr>
        <td><%= sensor.id %></td>
        <td><%= sensor.name %></td>
        <td><%= sensor.unit %></td>
        <td><%= sensor.kind %></td>
        <td><%= sensor.type_of_graph.humanize %></td>
        <td class="button-rows"><%= button_to 'Show', sensor, :method => "get", class: "btn-large waves-effect waves-light orange" %></td>
        <td class="button-rows"><%= button_to 'Edit', edit_sensor_path(sensor), :method => "get", class: "btn-large waves-effect waves-light orange" %></td>
        <td><%= button_to 'Delete',
                sensor, method: :delete, class: "btn-large waves-effect waves-light orange" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Sensor', new_sensor_path, :method => "get", class: "btn-large waves-effect waves-light orange"  %>

app/views/sensors/new.html.erb
<div class="section no-pad-bot" id="index-banner">
  <div class="container">

    <h1 class="header center orange-text">New Sensor</h1>
    <div class="row center">
      <h5 class="header col s12 light">

        <%= form_for @sensor, html: {class: "col s12"}  do |f| %>
          <% if @sensor.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

              <ul>
              <% @sensor.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="input-field col s12">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>

          <!-- In Sensor model, this is called kind -->
          <div class="input-field col s12">
            <select>
              <option value="" disabled selected>Choose your option</option>
              <option value="1">Temperature</option>
              <option value="2">Ultrasound</option>
              <option value="3">Motion</option>
            </select>
            <label>Type of Sensor</label>
          </div>

<!-- This is an example of a select helper tag -->
<!-- select("post", "person_id", Person.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Person'}) -->
          <div class="input-field col s12">
            <select>
              <option value="" disabled selected>Choose your option</option>
              <option value="1">Celsius</option>
              <option value="2">Fahrenheit</option>
              <option value="3">Feet</option>
              <option value="4">Inches</option>
              <option value="5">Centimeter</option>
            </select>
            <label>Sensor unit</label>
          </div>

          <div class="input-field col s12">
            <!-- Switch -->
            <div id="public-switch" class="switch">
              <label>
                Public
                <input type="checkbox">
                <span class="lever"></span>
                Private
              </label>
            </div>
          </div>

          <div class="input-field col s12">
            <select>
              <option value="" disabled selected>Choose your option</option>
              <option value="1">Bar Graph</option>
              <option value="2">Line Graph</option>
              <option value="3">Binary Graph</option>
            </select>
            <label>Type of Graph</label>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>

      </h5>
    </div>
  </div>
</div>

app/views/sensors/show.html.erb
<% if flash[:notice] %>
  <div class="row">
    <div class="col s12 m12">
      <div class="card-panel teal">
        <span class="white-text"><%= flash[:notice] %>
        </span>
      </div>
    </div>
  </div>
<% end %>

<div class="nav-buttons" style="padding-top: 2.5%;"><%= button_to 'Back', sensors_path, method: "get", class: "btn-large waves-effect waves-light orange" if current_user %></div>
<div class="nav-buttons"><%= button_to 'Edit ', edit_sensor_path(@sensor), method: "get", class: "btn-large waves-effect waves-light orange" if current_user %></div>

<%# image_tag @sensor.events.last.images.first.photo.url %>

  <!-- Bar Chart -->
<div class="row">
  <div class="col-xs-6">
    <h3>Sensor Data: <%= @sensor.name %></h3>
    <% if @sensor.straight_line_graph? %>
      <%= line_chart @graph_data, {library: {curveType: "none", hAxis: {format: @x_format}, vAxis: {title: @sensor.unit }}} %>
    <% elsif @sensor.curved_line_graph? %>
      <%= line_chart @graph_data, {library: {curveType: "function", hAxis: {format: @x_format}, vAxis: {title: @sensor.unit }}} %>
    <% elsif @sensor.timeline? %>
      <div class="timeline"><%= timeline @grouped_data, {library: {width: 1000, hAxis: {format: @x_format}}} if !@grouped_data.empty? %></div>
    <% else %>
      <%= line_chart @graph_data, {library: {curveType: "function", hAxis: {format: @x_format}, vAxis: {title: @sensor.unit }}} %>
    <% end %>
  </div>
</div>

<%= form_tag sensor_path, method: :get do %>
  <div class="container">
    <div class="row">
      <div class="input-field col s6">
        <select name = "axis_time">
          <option value="1" <%= "selected" if @axis_time == "1" %>>24 hour</option>
          <option value="2" <%= "selected" if @axis_time == "2" %>>Week</option>
          <option value="3" <%= "selected" if @axis_time == "3" %>>Month</option>
          <option value="4" <%= "selected" if @axis_time == "4" %>>Year</option>
        </select>
        <label>X-axis timeframe</label>
      </div>
      <div class="row center">
        <%= submit_tag 'Update', class: "btn-large waves-effect waves-light orange" %>
      </div>
      <% if @sensor.public %>
        <div class="row">
          Your public link: <%= link_to sensor_url %>
        </div>
      <% end %>
      <% @sensor.events.reverse_each do | event | %>
        <% if event.images.count >= 1 %>

          <div class="col s12 m2">
            <div class="card">
              <div class="card-image">
                <%= link_to(image_tag(event.images.first.photo.url(:thumb)), event.images.first.photo.url(:original)) %>
              </div>
            </div>
          </div>

        <% end %>
      <% end %>
    </div>
  </div>
<% end %>