config/routes.rb
Rails.application.routes.draw do
  post 'events/create'
  get 'events/show'

  root 'welcome#index'
  get '/gettingstarted', to: 'welcome#gettingstarted' 

  resources :sensors
  resources :notes
  resources :sessions
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sensoree</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <!-- Compiled and minified CSS -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
 <!-- Compiled and minified JavaScript -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</head>
  <body>

    <nav style="color: teal;">
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo" style="padding-left: 2.5%;">
          <i class="large material-icons" style="color: white;">settings_input_antenna</i>
        </a>
        <a href="#" data-activates="mobile-demo"
                    class="button-collapse"><i class="material-icons" style="color: white;">menu</i></a>
        <ul class="right hide-on-med-and-down">

          <li><%= link_to 'Getting Started', gettingstarted_path %></li>
          <li><%= link_to 'Sign in', new_session_path  %></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><%= link_to 'Getting Started', gettingstarted_path %></li>

          <li><%= link_to 'Sign in', new_session_path %></li>
          
        </ul>
      </div>
    </nav>

    <%= yield %>

    <footer class="page-footer teal">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <p class="grey-text text-lighten-4">A project designed by students, for students. Designed and developed in Ft. Lauderdale, FL</p>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        Created by <a class="brown-text text-lighten-3" href="http://www.linkedin.com/in/dkarim">David Karim</a> &#38; <a class="brown-text text-lighten-3" href="#">Juan Perez</a>
        </div>
      </div>
    </footer>


  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sensoree</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag "application", "chartkick" %>
  <%= csrf_meta_tags %>
  <!-- Compiled and minified CSS -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
 <!-- Compiled and minified JavaScript -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</head>
<body>
  <nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo" style="padding-left: 2.5%;">
      <i class="large material-icons" style="color: white;">settings_input_antenna</i>
    </a>
    <a href="#" data-activates="mobile-demo"
          class="button-collapse"><i
          class="material-icons" style="color: white;">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to 'Account', edit_user_path(current_user) if current_user %></li>
    
      <li><%= link_to 'Logout', root_path if current_user %></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to 'Account', edit_user_path(current_user) if current_user %></li>

      <li><%= link_to 'Logout', root_path if current_user %></li>
    </ul>
  </div>
</nav>

<%= yield %>

<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <p class="grey-text text-lighten-4">A project designed by students, for students. Designed and developed in Ft. Lauderdale, FL</p>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    Created by <a class="brown-text text-lighten-3" href="http://www.linkedin.com/in/dkarim">David Karim</a> &#38; <a class="brown-text text-lighten-3" href="#">Juan Perez</a>
    </div>
  </div>
</footer>


</body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sensoree</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Compiled and minified CSS -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
 <!-- Compiled and minified JavaScript -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</head>
<body>
  <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo" style="padding-left: 2.5%;">
        <i class="large material-icons" style="color: white;">settings_input_antenna</i>
      </a>
      <a href="#" data-activates="mobile-demo"
                  class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#"><%= link_to 'Sensors', sensors_path(current_user) %></li>
        <li><%= link_to 'Back', root_path %></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="#"><%= link_to 'Sensors', sensors_path(current_user) %></li>
        <li><%= link_to 'Back', root_path %></li>

      </ul>
    </div>
  </nav>

<%= yield %>

<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <p class="grey-text text-lighten-4">A project designed by students, for students. Designed and developed in Ft. Lauderdale, FL</p>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    Created by <a class="brown-text text-lighten-3" href="http://www.linkedin.com/in/dkarim">David Karim</a> &#38; <a class="brown-text text-lighten-3" href="#">Juan Perez</a>
    </div>
  </div>
</footer>


</body>
</html>